- hosts: all
  become: True
  tasks:
    - name: 'setup'
      setup:
        filter: '*'

- hosts: all
  become: True
  roles:
    - { role: fail2ban, tags: [ 'fail2ban' ] }
    - { role: iptables, tags: [ 'iptables' ] }
    - { role: postfix, tags: [ 'postfix' ] }
    - { role: tripwire, tags: [ 'tripwire' ] }
