---
- name: install
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
  - fail2ban

- name: make a local configuration
  shell: awk '{ print; }' /etc/fail2ban/jail.conf | tee /etc/fail2ban/jail.local creates=/etc/fail2ban/jail.local

- name: change the configuration
  ini_file:
    dest: "/etc/fail2ban/jail.local"
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - {section: 'DEFAULT', option: 'bantime', value: '{{fail2ban_ban_time}}'}
    - {section: 'DEFAULT', option: 'action', value: '%(action_mwl)s'}
    - {section: 'DEFAULT', option: 'mta', value: 'mail'}
    - {section: 'DEFAULT', option: 'destemail', value: 'root'}
  notify:
    - restart fail2ban
